org.gradle.jvmargs=-Xmx8G
minecraft_version=26.2
snapshot_version=26.2
loader_version=0.19.3
mod_id=bettercopperage
mod_version=1.5-Fabric
mod_name=Hendrix's Better Copper Age
mod_description=Make Copper Golems interact with Copper Buttons, like originally intended, and boost your builds with new decorative blocks!
mod_author=JimiIT92,JDG
mod_url=https://github.com/JimiIT92/BetterCopperAge
maven_group=org.hendrix.bettercopperage
archives_base_name=BetterCopperAge
fabric_version=0.152.1
loom_version=1.17-SNAPSHOT